// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.EFCore;

#nullable disable

namespace bsStoreBook.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20251013140325_CreateBookClass")]
    partial class CreateBookClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 154m,
                            Title = "C# Programming"
                        },
                        new
                        {
                            Id = 2,
                            Price = 200m,
                            Title = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 3,
                            Price = 180m,
                            Title = "Entity Framework Core"
                        },
                        new
                        {
                            Id = 4,
                            Price = 220m,
                            Title = "Blazor Development"
                        },
                        new
                        {
                            Id = 5,
                            Price = 300m,
                            Title = "Microservices Architecture"
                        },
                        new
                        {
                            Id = 6,
                            Price = 250m,
                            Title = "Design Patterns in C#"
                        },
                        new
                        {
                            Id = 7,
                            Price = 275m,
                            Title = "Azure for Developers"
                        },
                        new
                        {
                            Id = 8,
                            Price = 320m,
                            Title = "Docker and Kubernetes"
                        },
                        new
                        {
                            Id = 9,
                            Price = 190m,
                            Title = "Unit Testing in .NET"
                        },
                        new
                        {
                            Id = 10,
                            Price = 210m,
                            Title = "Web API Development"
                        },
                        new
                        {
                            Id = 11,
                            Price = 160m,
                            Title = "LINQ Fundamentals"
                        },
                        new
                        {
                            Id = 12,
                            Price = 230m,
                            Title = "C# Advanced Topics"
                        },
                        new
                        {
                            Id = 13,
                            Price = 280m,
                            Title = "Performance Optimization in .NET"
                        },
                        new
                        {
                            Id = 14,
                            Price = 240m,
                            Title = "Security Best Practices"
                        },
                        new
                        {
                            Id = 15,
                            Price = 260m,
                            Title = "DevOps with .NET"
                        },
                        new
                        {
                            Id = 16,
                            Price = 290m,
                            Title = "Mobile App Development with Xamarin"
                        },
                        new
                        {
                            Id = 17,
                            Price = 195m,
                            Title = "WPF for Desktop Applications"
                        },
                        new
                        {
                            Id = 18,
                            Price = 225m,
                            Title = "SignalR for Real-time Applications"
                        },
                        new
                        {
                            Id = 19,
                            Price = 150m,
                            Title = "C# for Beginners"
                        },
                        new
                        {
                            Id = 20,
                            Price = 310m,
                            Title = "Refactoring Legacy Code"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
